site:
  title: Datanexions Docs
  start_page: streams::index.adoc

content:
  sources:
    - url: ./docs/streams
      branches: main

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/main/raw/build/ui-bundle.zip?job=build

output:
  dir: ./build/site