// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  streamsSidebar: [
    {
      type: 'category',
      label: '01. Getting Started',
      collapsed: false,
      items: [
        'streams/getting-started/overview',
        'streams/getting-started/installation',
        'streams/getting-started/quick-start',
      ],
    },
    {
      type: 'category',
      label: '02. Core Concepts',
      collapsed: false,
      items: [
        'streams/core-concepts/architecture',
        'streams/core-concepts/projects',
        'streams/core-concepts/connections',
        'streams/core-concepts/scopes',
        'streams/core-concepts/streams',
        'streams/core-concepts/models',
      ],
    },
    {
      type: 'category',
      label: '03. Configuration',
      collapsed: true,
      items: [
        'streams/configuration/environment',
        'streams/configuration/target-database',
        'streams/configuration/project-config',
        'streams/configuration/variants',
      ],
    },
    {
      type: 'category',
      label: '04. Stream Design',
      collapsed: true,
      items: [
        'streams/stream-design/overview',
        'streams/stream-design/columns',
        'streams/stream-design/create-operations',
        'streams/stream-design/update-operations',
        'streams/stream-design/formulas',
        'streams/stream-design/aggregations',
      ],
    },
    {
      type: 'category',
      label: '05. Data Governance',
      collapsed: true,
      items: [
        'streams/data-governance/glossary',
        'streams/data-governance/validation-rules',
      ],
    },
    {
      type: 'category',
      label: '06. Reference',
      collapsed: true,
      items: [
        'streams/reference/connection-types',
        'streams/reference/content-types',
        'streams/reference/field-types',
        'streams/reference/create-connector',
      ],
    },
    {
      type: 'category',
      label: '07. Examples',
      collapsed: true,
      items: [
        'streams/examples/example-excel-to-couchbase',
        'streams/examples/example-database-join',
        'streams/examples/example-formulas',
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;