// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  streamsSidebar: [
    { type: 'doc', id: 'streams/intro', label: 'Introduction' },
    { type: 'doc', id: 'streams/configuration', label: 'Configuration' },
    { type: 'doc', id: 'streams/examples', label: 'Examples' },
    { type: 'doc', id: 'streams/connections', label: 'Connections' },
    { type: 'doc', id: 'streams/create_connector', label: 'Create Connector' },
    { type: 'doc', id: 'streams/glossary', label: 'Glossary' },
    { type: 'doc', id: 'streams/streams_part1', label: 'Streams Part 1' },
    { type: 'doc', id: 'streams/streams_part2', label: 'Streams Part 2' },
    {
      type: 'category',
      label: 'DSL',
      items: [
        'streams/dsl/dsl-overview',
        'streams/dsl/dsl-syntax',
      ],
    }
  ],
  connectSidebar: [
      'connect/intro',
      'connect/configuration',
      'connect/examples',
  ],
  bookingsSidebar: [
      'bookings/intro',
      'bookings/configuration',
      'bookings/examples',
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
